//
// Created by knx2header.py
//
// DO NOT EDIT THIS FILE. IT WILL BE OVERWRITTEN!
//
    
#ifndef INC_LIGHTSENSOR_PARAMS_H
#define INC_LIGHTSENSOR_PARAMS_H

#define userEeprom (*(bcu.userEeprom))

/**
	@brief ja_nein Bits: 1
		@ref JA_NEIN_NO (0): no
		@ref JA_NEIN_YES (1): yes
*/
enum JA_NEIN {
 	JA_NEIN_NO = 0
,	JA_NEIN_YES = 1
};

/**
	@brief device_typ Bits: 1
		@ref DEVICE_TYP_MULTIPLEX (0): multiplex
		@ref DEVICE_TYP_DIRECT_I_O (1): direct i/o
*/
enum DEVICE_TYP {
 	DEVICE_TYP_MULTIPLEX = 0
,	DEVICE_TYP_DIRECT_I_O = 1
};

/**
	@brief sensor_typ Bits: 2
		@ref SENSOR_TYP_NO_SENSOR (0): no sensor
		@ref SENSOR_TYP_TEMPERATURE_SENSOR (1): lux sensor
		@ref SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR (2): lux/humidity sensor
*/
enum SENSOR_TYP {
 	SENSOR_TYP_NO_SENSOR = 0
,	SENSOR_TYP_TEMPERATURE_SENSOR = 1
,	SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR = 2
};

/**
	@brief sensor_temperatur Bits: 1
		@ref SENSOR_TEMPERATUR_DS18B20 (0): DS18B20
		@ref SENSOR_TEMPERATUR_DS18S20 (1): DS18S20
*/
enum SENSOR_TEMPERATUR {
 	SENSOR_TEMPERATUR_DS18B20 = 0
,	SENSOR_TEMPERATUR_DS18S20 = 1
};

/**
	@brief sensor_feuchtigkeit Bits: 1
		@ref SENSOR_FEUCHTIGKEIT_DTH11 (1): DTH11
		@ref SENSOR_FEUCHTIGKEIT_DTH22 (0): DTH22
*/
enum SENSOR_FEUCHTIGKEIT {
 	SENSOR_FEUCHTIGKEIT_DTH11 = 1
,	SENSOR_FEUCHTIGKEIT_DTH22 = 0
};

/**
	@brief grenzwert_reaktion Bits: 4
		@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
		@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
		@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
		@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
		@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
		@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
		@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
		@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
		@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
enum GRENZWERT_REAKTION {
 	GRENZWERT_REAKTION_DEACTIVATED = 0
,	GRENZWERT_REAKTION_FALLS_BELOW_0 = 2
,	GRENZWERT_REAKTION_FALLS_BELOW_1 = 3
,	GRENZWERT_REAKTION_EXCEED_0 = 8
,	GRENZWERT_REAKTION_EXCEED_1 = 12
,	GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 = 14
,	GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 = 11
,	GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 = 10
,	GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 = 15
};

/**
	@brief grenzwert_zuordnung Bits: 2
		@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
		@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
enum GRENZWERT_ZUORDNUNG {
 	GRENZWERT_ZUORDNUNG_TEMPERATURE = 1
,	GRENZWERT_ZUORDNUNG_HUMIDITY = 2
};

/**
	@brief timer_basis Bits: 4
		@ref TIMER_BASIS_130_MS (0): 130 ms
		@ref TIMER_BASIS_260_MS (1): 260 ms
		@ref TIMER_BASIS_520_MS (2): 520 ms
		@ref TIMER_BASIS_1_0_S (3): 1.0 s
		@ref TIMER_BASIS_2_1_S (4): 2.1 s
		@ref TIMER_BASIS_4_2_S (5): 4.2 s
		@ref TIMER_BASIS_8_4_S (6): 8.4 s
		@ref TIMER_BASIS_17_S (7): 17 s
		@ref TIMER_BASIS_34_S (8): 34 s
		@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
		@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
		@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
		@ref TIMER_BASIS_9_MIN (12): 9 min
		@ref TIMER_BASIS_18_MIN (13): 18 min
		@ref TIMER_BASIS_35_MIN (14): 35 min
		@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
enum TIMER_BASIS {
 	TIMER_BASIS_130_MS = 0
,	TIMER_BASIS_260_MS = 1
,	TIMER_BASIS_520_MS = 2
,	TIMER_BASIS_1_0_S = 3
,	TIMER_BASIS_2_1_S = 4
,	TIMER_BASIS_4_2_S = 5
,	TIMER_BASIS_8_4_S = 6
,	TIMER_BASIS_17_S = 7
,	TIMER_BASIS_34_S = 8
,	TIMER_BASIS_1_1_MIN = 9
,	TIMER_BASIS_2_2_MIN = 10
,	TIMER_BASIS_4_5_MIN = 11
,	TIMER_BASIS_9_MIN = 12
,	TIMER_BASIS_18_MIN = 13
,	TIMER_BASIS_35_MIN = 14
,	TIMER_BASIS_1_2_H = 15
};

/**
	@brief init_mw Bits: 1
		@ref INIT_MW_DO_NOT_SEND (0): do not send
		@ref INIT_MW_SENT_WITH_DELAY (1): sent with delay
*/
enum INIT_MW {
 	INIT_MW_DO_NOT_SEND = 0
,	INIT_MW_SENT_WITH_DELAY = 1
};

/**
	@brief init_gw Bits: 2
		@ref INIT_GW_DO_NOT_SEND (0): do not send
		@ref INIT_GW_SENT_IMMEDIATELY (1): sent immediately
		@ref INIT_GW_SEND_DELAYED (2): send delayed
*/
enum INIT_GW {
 	INIT_GW_DO_NOT_SEND = 0
,	INIT_GW_SENT_IMMEDIATELY = 1
,	INIT_GW_SEND_DELAYED = 2
};

/**
	@brief sendetyp_mw Bits: 1
		@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
		@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
enum SENDETYP_MW {
 	SENDETYP_MW_DPT9_EIS5_DEFAULT = 0
,	SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT = 1
};

/**
	@brief freig_sperr Bits: 1
		@ref FREIG_SPERR_UNLOCKED (1): unlocked
		@ref FREIG_SPERR_LOCKED (0): locked
*/
enum FREIG_SPERR {
 	FREIG_SPERR_UNLOCKED = 1
,	FREIG_SPERR_LOCKED = 0
};

/**
	@brief timer_start_base Bits: 4
		@ref TIMER_START_BASE_8 (1): 8
		@ref TIMER_START_BASE_16 (2): 16
		@ref TIMER_START_BASE_24 (3): 24
		@ref TIMER_START_BASE_32 (4): 32
		@ref TIMER_START_BASE_40 (5): 40
		@ref TIMER_START_BASE_48 (6): 48
		@ref TIMER_START_BASE_56 (7): 56
		@ref TIMER_START_BASE_64 (8): 64
		@ref TIMER_START_BASE_72 (9): 72
		@ref TIMER_START_BASE_80 (10): 80
		@ref TIMER_START_BASE_88 (11): 88
		@ref TIMER_START_BASE_96 (12): 96
		@ref TIMER_START_BASE_104 (13): 104
		@ref TIMER_START_BASE_112 (14): 112
		@ref TIMER_START_BASE_127 (15): 127
*/
enum TIMER_START_BASE {
 	TIMER_START_BASE_8 = 1
,	TIMER_START_BASE_16 = 2
,	TIMER_START_BASE_24 = 3
,	TIMER_START_BASE_32 = 4
,	TIMER_START_BASE_40 = 5
,	TIMER_START_BASE_48 = 6
,	TIMER_START_BASE_56 = 7
,	TIMER_START_BASE_64 = 8
,	TIMER_START_BASE_72 = 9
,	TIMER_START_BASE_80 = 10
,	TIMER_START_BASE_88 = 11
,	TIMER_START_BASE_96 = 12
,	TIMER_START_BASE_104 = 13
,	TIMER_START_BASE_112 = 14
,	TIMER_START_BASE_127 = 15
};

/**
 * Com Object Enums
 */
enum COM {
	/**
	@li "Temperature", "Send lux as", "Sensor 1"
	  Temperature - Sensor 1
	  ObjectSize: 2 Bytes
	*/
	COM_TEMPERATURE_SEND_TEMPERATURE_AS_SENSOR_1 = 0
	/**
	@li "Humidity", "Send humidity as", "Sensor 1"
	  Humidity - Sensor 1
	  ObjectSize: 2 Bytes
	*/
,	COM_HUMIDITY_SEND_HUMIDITY_AS_SENSOR_1 = 1
	/**
	@li "Temperature", "Send lux as", "Sensor 2"
	  Temperature - Sensor 2
	  ObjectSize: 2 Bytes
	*/
,	COM_TEMPERATURE_SEND_TEMPERATURE_AS_SENSOR_2 = 2
	/**
	@li "Humidity", "Send humidity as", "Sensor 2"
	  Humidity - Sensor 2
	  ObjectSize: 2 Bytes
	*/
,	COM_HUMIDITY_SEND_HUMIDITY_AS_SENSOR_2 = 3
	/**
	@li "Temperature", "Send lux as", "Sensor 3"
	  Temperature - Sensor 3
	  ObjectSize: 2 Bytes
	*/
,	COM_TEMPERATURE_SEND_TEMPERATURE_AS_SENSOR_3 = 4
	/**
	@li "Humidity", "Send humidity as", "Sensor 3"
	  Humidity - Sensor 3
	  ObjectSize: 2 Bytes
	*/
,	COM_HUMIDITY_SEND_HUMIDITY_AS_SENSOR_3 = 5
	/**
	@li "Temperature", "Send lux as", "Sensor 4"
	  Temperature - Sensor 4
	  ObjectSize: 2 Bytes
	*/
,	COM_TEMPERATURE_SEND_TEMPERATURE_AS_SENSOR_4 = 6
	/**
	@li "Humidity", "Send humidity as", "Sensor 4"
	  Humidity - Sensor 4
	  ObjectSize: 2 Bytes
	*/
,	COM_HUMIDITY_SEND_HUMIDITY_AS_SENSOR_4 = 7
	/**
	@li "Threshold 1 lux", "Threshold 1", "Sensor 1"
	  Threshold 1 lux - Sensor 1
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_1_TEMPERATURE_THRESHOLD_1_SENSOR_1 = 8
	/**
	@li "Threshold 2 lux", "Threshold 2", "Sensor 1"
	  Threshold 2 lux - Sensor 1
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_2_TEMPERATURE_THRESHOLD_2_SENSOR_1 = 9
	/**
	@li "Threshold 3 lux", "Threshold 3", "Sensor 1"
	  Threshold 3 lux - Sensor 1
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_3_TEMPERATURE_THRESHOLD_3_SENSOR_1 = 10
	/**
	@li "Threshold 1 lux", "Threshold 1", "Sensor 2"
	  Threshold 1 lux - Sensor 2
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_1_TEMPERATURE_THRESHOLD_1_SENSOR_2 = 11
	/**
	@li "Threshold 2 lux", "Threshold 2", "Sensor 2"
	  Threshold 2 lux - Sensor 2
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_2_TEMPERATURE_THRESHOLD_2_SENSOR_2 = 12
	/**
	@li "Threshold 3 lux", "Threshold 3", "Sensor 2"
	  Threshold 3 lux - Sensor 2
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_3_TEMPERATURE_THRESHOLD_3_SENSOR_2 = 13
	/**
	@li "Threshold 1 lux", "Threshold 1", "Sensor 3"
	  Threshold 1 lux - Sensor 3
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_1_TEMPERATURE_THRESHOLD_1_SENSOR_3 = 14
	/**
	@li "Threshold 2 lux", "Threshold 2", "Sensor 3"
	  Threshold 2 lux - Sensor 3
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_2_TEMPERATURE_THRESHOLD_2_SENSOR_3 = 15
	/**
	@li "Threshold 3 lux", "Threshold 3", "Sensor 3"
	  Threshold 3 lux - Sensor 3
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_3_TEMPERATURE_THRESHOLD_3_SENSOR_3 = 16
	/**
	@li "Threshold 1 lux", "Threshold 1", "Sensor 4"
	  Threshold 1 lux - Sensor 4
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_1_TEMPERATURE_THRESHOLD_1_SENSOR_4 = 17
	/**
	@li "Threshold 2 lux", "Threshold 2", "Sensor 4"
	  Threshold 2 lux - Sensor 4
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_2_TEMPERATURE_THRESHOLD_2_SENSOR_4 = 18
	/**
	@li "Threshold 3 lux", "Threshold 3", "Sensor 4"
	  Threshold 3 lux - Sensor 4
	  ObjectSize: 1 Bit
	*/
,	COM_THRESHOLD_3_TEMPERATURE_THRESHOLD_3_SENSOR_4 = 19
	/**
	@li "Diagnosis", "Diagnosis"
	  Diagnosis - Diagnose Modus
	  ObjectSize: 4 Bytes
	*/
,	COM_DIAGNOSIS_DIAGNOSIS = 20
};

/**
		@brief Address: 01b1
		@li "Diagnosis"
		@b Default: 0
			@brief freig_sperr Bits: 1
				@ref FREIG_SPERR_UNLOCKED (1): unlocked
				@ref FREIG_SPERR_LOCKED (0): locked
*/
#define EE_DIAGNOSIS ((unsigned)userEeprom[0x01b1] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b1 BitOffset:1
		@li "Bus Recovery Threshold Temp Timefactor"
		@b Default: 80
			@brief timer_start_fak Bits: 7 Type: unsignedInt from 1 to 127
*/
#define EE_BUS_RECOVERY_THRESHOLD_TEMP_TIMEFACTOR (userEeprom[0x01b1] &~ (-1u << 7u))

/**
		@brief Address: 01b2
		@li "Threshold lux", "Sensor 4"
		@b Default: 0
			@brief init_gw Bits: 2
				@ref INIT_GW_DO_NOT_SEND (0): do not send
				@ref INIT_GW_SENT_IMMEDIATELY (1): sent immediately
				@ref INIT_GW_SEND_DELAYED (2): send delayed
*/
#define EE_THRESHOLD_TEMPERATURE_SENSOR_4 ((unsigned)userEeprom[0x01b2] >> 6u &~ (-1u << 2u))

/**
		@brief Address: 01b2 BitOffset:2
		@li "Threshold lux", "Sensor 3"
		@b Default: 0
			@brief init_gw Bits: 2
				@ref INIT_GW_DO_NOT_SEND (0): do not send
				@ref INIT_GW_SENT_IMMEDIATELY (1): sent immediately
				@ref INIT_GW_SEND_DELAYED (2): send delayed
*/
#define EE_THRESHOLD_TEMPERATURE_SENSOR_3 ((unsigned)userEeprom[0x01b2] >> 4u &~ (-1u << 2u))

/**
		@brief Address: 01b2 BitOffset:4
		@li "Threshold lux", "Sensor 2"
		@b Default: 0
			@brief init_gw Bits: 2
				@ref INIT_GW_DO_NOT_SEND (0): do not send
				@ref INIT_GW_SENT_IMMEDIATELY (1): sent immediately
				@ref INIT_GW_SEND_DELAYED (2): send delayed
*/
#define EE_THRESHOLD_TEMPERATURE_SENSOR_2 ((unsigned)userEeprom[0x01b2] >> 2u &~ (-1u << 2u))

/**
		@brief Address: 01b2 BitOffset:6
		@li "Threshold lux", "Sensor 1"
		@b Default: 0
			@brief init_gw Bits: 2
				@ref INIT_GW_DO_NOT_SEND (0): do not send
				@ref INIT_GW_SENT_IMMEDIATELY (1): sent immediately
				@ref INIT_GW_SEND_DELAYED (2): send delayed
*/
#define EE_THRESHOLD_TEMPERATURE_SENSOR_1 (userEeprom[0x01b2] &~ (-1u << 2u))

/**
		@brief Address: 01b3
		@li "Measurement value temp", "Sensor 1"
		@b Default: 0
			@brief init_mw Bits: 1
				@ref INIT_MW_DO_NOT_SEND (0): do not send
				@ref INIT_MW_SENT_WITH_DELAY (1): sent with delay
*/
#define EE_MEASUREMENT_VALUE_TEMP_SENSOR_1 ((unsigned)userEeprom[0x01b3] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b3 BitOffset:1
		@li "Time factor meas. value", "Sensor 1"
		@b Default: 5
			@brief timer_start_fak Bits: 7 Type: unsignedInt from 1 to 127
*/
#define EE_TIME_FACTOR_MEAS_VALUE_SENSOR_1 (userEeprom[0x01b3] &~ (-1u << 7u))

/**
		@brief Address: 01b4
		@li "Measurement value temp", "Sensor 2"
		@b Default: 0
			@brief init_mw Bits: 1
				@ref INIT_MW_DO_NOT_SEND (0): do not send
				@ref INIT_MW_SENT_WITH_DELAY (1): sent with delay
*/
#define EE_MEASUREMENT_VALUE_TEMP_SENSOR_2 ((unsigned)userEeprom[0x01b4] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b4 BitOffset:1
		@li "Time factor meas. value", "Sensor 2"
		@b Default: 6
			@brief timer_start_fak Bits: 7 Type: unsignedInt from 1 to 127
*/
#define EE_TIME_FACTOR_MEAS_VALUE_SENSOR_2 (userEeprom[0x01b4] &~ (-1u << 7u))

/**
		@brief Address: 01b5
		@li "Measurement value temp", "Sensor 3"
		@b Default: 0
			@brief init_mw Bits: 1
				@ref INIT_MW_DO_NOT_SEND (0): do not send
				@ref INIT_MW_SENT_WITH_DELAY (1): sent with delay
*/
#define EE_MEASUREMENT_VALUE_TEMP_SENSOR_3 ((unsigned)userEeprom[0x01b5] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b5 BitOffset:1
		@li "Time factor meas. value", "Sensor 3"
		@b Default: 5
			@brief timer_start_fak Bits: 7 Type: unsignedInt from 1 to 127
*/
#define EE_TIME_FACTOR_MEAS_VALUE_SENSOR_3 (userEeprom[0x01b5] &~ (-1u << 7u))

/**
		@brief Address: 01b6
		@li "Measurement value temp", "Sensor 4"
		@b Default: 0
			@brief init_mw Bits: 1
				@ref INIT_MW_DO_NOT_SEND (0): do not send
				@ref INIT_MW_SENT_WITH_DELAY (1): sent with delay
*/
#define EE_MEASUREMENT_VALUE_TEMP_SENSOR_4 ((unsigned)userEeprom[0x01b6] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b6 BitOffset:1
		@li "Time factor meas. value", "Sensor 4"
		@b Default: 5
			@brief timer_start_fak Bits: 7 Type: unsignedInt from 1 to 127
*/
#define EE_TIME_FACTOR_MEAS_VALUE_SENSOR_4 (userEeprom[0x01b6] &~ (-1u << 7u))

/**
		@brief Address: 01b7
		@li "Send humidity as", "Sensor 1"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_HUMIDITY_AS_SENSOR_1 ((unsigned)userEeprom[0x01b7] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b7 BitOffset:1
		@li "Send lux as", "Sensor 1"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_TEMPERATURE_AS_SENSOR_1 ((unsigned)userEeprom[0x01b7] >> 6u &~ (-1u << 1u))

/**
		@brief Address: 01b7 BitOffset:4
		@li "Sensor type", "Sensor 1"
		@b Default: 0
			@brief sensor_feuchtigkeit Bits: 1
				@ref SENSOR_FEUCHTIGKEIT_DTH11 (1): DTH11
				@ref SENSOR_FEUCHTIGKEIT_DTH22 (0): DTH22
*/
#define EE_SENSOR_TYPE_SENSOR_1 ((unsigned)userEeprom[0x01b7] >> 3u &~ (-1u << 1u))

/**
		@brief Address: 01b7 BitOffset:5
		@li "T Sensor type", "Sensor 1"
		@b Default: 0
			@brief sensor_temperatur Bits: 1
				@ref SENSOR_TEMPERATUR_DS18B20 (0): DS18B20
				@ref SENSOR_TEMPERATUR_DS18S20 (1): DS18S20
*/
#define EE_T_SENSOR_TYPE_SENSOR_1 ((unsigned)userEeprom[0x01b7] >> 2u &~ (-1u << 1u))

/**
		@brief Address: 01b7 BitOffset:6
		@li "Type", "Sensor 1"
		@b Default: 0
			@brief sensor_typ Bits: 2
				@ref SENSOR_TYP_NO_SENSOR (0): no sensor
				@ref SENSOR_TYP_TEMPERATURE_SENSOR (1): lux sensor
				@ref SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR (2): lux/humidity sensor
*/
#define EE_TYPE_SENSOR_1 (userEeprom[0x01b7] &~ (-1u << 2u))

/**
		@brief Address: 01b8
		@li "Send humidity as", "Sensor 2"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_HUMIDITY_AS_SENSOR_2 ((unsigned)userEeprom[0x01b8] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b8 BitOffset:1
		@li "Send lux as", "Sensor 2"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_TEMPERATURE_AS_SENSOR_2 ((unsigned)userEeprom[0x01b8] >> 6u &~ (-1u << 1u))

/**
		@brief Address: 01b8 BitOffset:4
		@li "Sensor type", "Sensor 2"
		@b Default: 0
			@brief sensor_feuchtigkeit Bits: 1
				@ref SENSOR_FEUCHTIGKEIT_DTH11 (1): DTH11
				@ref SENSOR_FEUCHTIGKEIT_DTH22 (0): DTH22
*/
#define EE_SENSOR_TYPE_SENSOR_2 ((unsigned)userEeprom[0x01b8] >> 3u &~ (-1u << 1u))

/**
		@brief Address: 01b8 BitOffset:5
		@li "T Sensor type", "Sensor 2"
		@b Default: 0
			@brief sensor_temperatur Bits: 1
				@ref SENSOR_TEMPERATUR_DS18B20 (0): DS18B20
				@ref SENSOR_TEMPERATUR_DS18S20 (1): DS18S20
*/
#define EE_T_SENSOR_TYPE_SENSOR_2 ((unsigned)userEeprom[0x01b8] >> 2u &~ (-1u << 1u))

/**
		@brief Address: 01b8 BitOffset:6
		@li "Type", "Sensor 2"
		@b Default: 0
			@brief sensor_typ Bits: 2
				@ref SENSOR_TYP_NO_SENSOR (0): no sensor
				@ref SENSOR_TYP_TEMPERATURE_SENSOR (1): lux sensor
				@ref SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR (2): lux/humidity sensor
*/
#define EE_TYPE_SENSOR_2 (userEeprom[0x01b8] &~ (-1u << 2u))

/**
		@brief Address: 01b9
		@li "Send humidity as", "Sensor 3"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_HUMIDITY_AS_SENSOR_3 ((unsigned)userEeprom[0x01b9] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01b9 BitOffset:1
		@li "Send lux as", "Sensor 3"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_TEMPERATURE_AS_SENSOR_3 ((unsigned)userEeprom[0x01b9] >> 6u &~ (-1u << 1u))

/**
		@brief Address: 01b9 BitOffset:4
		@li "Sensor type", "Sensor 3"
		@b Default: 0
			@brief sensor_feuchtigkeit Bits: 1
				@ref SENSOR_FEUCHTIGKEIT_DTH11 (1): DTH11
				@ref SENSOR_FEUCHTIGKEIT_DTH22 (0): DTH22
*/
#define EE_SENSOR_TYPE_SENSOR_3 ((unsigned)userEeprom[0x01b9] >> 3u &~ (-1u << 1u))

/**
		@brief Address: 01b9 BitOffset:5
		@li "T Sensor type", "Sensor 3"
		@b Default: 0
			@brief sensor_temperatur Bits: 1
				@ref SENSOR_TEMPERATUR_DS18B20 (0): DS18B20
				@ref SENSOR_TEMPERATUR_DS18S20 (1): DS18S20
*/
#define EE_T_SENSOR_TYPE_SENSOR_3 ((unsigned)userEeprom[0x01b9] >> 2u &~ (-1u << 1u))

/**
		@brief Address: 01b9 BitOffset:6
		@li "Type", "Sensor 3"
		@b Default: 0
			@brief sensor_typ Bits: 2
				@ref SENSOR_TYP_NO_SENSOR (0): no sensor
				@ref SENSOR_TYP_TEMPERATURE_SENSOR (1): lux sensor
				@ref SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR (2): lux/humidity sensor
*/
#define EE_TYPE_SENSOR_3 (userEeprom[0x01b9] &~ (-1u << 2u))

/**
		@brief Address: 01ba
		@li "Send humidity as", "Sensor 4"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_HUMIDITY_AS_SENSOR_4 ((unsigned)userEeprom[0x01ba] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01ba BitOffset:1
		@li "Send lux as", "Sensor 4"
		@b Default: 0
			@brief sendetyp_mw Bits: 1
				@ref SENDETYP_MW_DPT9_EIS5_DEFAULT (0): DPT9 /EIS5 (default)
				@ref SENDETYP_MW_DPT5_EIS6_NON_STANDARD_COMPLIANT (1): DPT5 /EIS6 (non standard compliant!)
*/
#define EE_SEND_TEMPERATURE_AS_SENSOR_4 ((unsigned)userEeprom[0x01ba] >> 6u &~ (-1u << 1u))

/**
		@brief Address: 01ba BitOffset:4
		@li "Sensor type", "Sensor 4"
		@b Default: 0
			@brief sensor_feuchtigkeit Bits: 1
				@ref SENSOR_FEUCHTIGKEIT_DTH11 (1): DTH11
				@ref SENSOR_FEUCHTIGKEIT_DTH22 (0): DTH22
*/
#define EE_SENSOR_TYPE_SENSOR_4 ((unsigned)userEeprom[0x01ba] >> 3u &~ (-1u << 1u))

/**
		@brief Address: 01ba BitOffset:5
		@li "T Sensor type", "Sensor 4"
		@b Default: 0
			@brief sensor_temperatur Bits: 1
				@ref SENSOR_TEMPERATUR_DS18B20 (0): DS18B20
				@ref SENSOR_TEMPERATUR_DS18S20 (1): DS18S20
*/
#define EE_T_SENSOR_TYPE_SENSOR_4 ((unsigned)userEeprom[0x01ba] >> 2u &~ (-1u << 1u))

/**
		@brief Address: 01ba BitOffset:6
		@li "Type", "Sensor 4"
		@b Default: 0
			@brief sensor_typ Bits: 2
				@ref SENSOR_TYP_NO_SENSOR (0): no sensor
				@ref SENSOR_TYP_TEMPERATURE_SENSOR (1): lux sensor
				@ref SENSOR_TYP_TEMPERATURE_HUMIDITY_SENSOR (2): lux/humidity sensor
*/
#define EE_TYPE_SENSOR_4 (userEeprom[0x01ba] &~ (-1u << 2u))

/**
		@brief Address: 01bb
		@li "Temperature factor in 0.1K", "Sensor 1"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_TEMPERATURE_OFFSET_IN_0_1K_SENSOR_1 (userEeprom[0x01bb])

/**
		@brief Address: 01bc
		@li "Humidity factor in 0.1%", "Humidity", "Sensor 1"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_HUMIDITY_OFFSET_IN_0_1_HUMIDITY_SENSOR_1 (userEeprom[0x01bc])

/**
		@brief Address: 01bd
		@li "Temperature factor in 0.1K", "Sensor 2"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_TEMPERATURE_OFFSET_IN_0_1K_SENSOR_2 (userEeprom[0x01bd])

/**
		@brief Address: 01be
		@li "Humidity factor in 0.1%", "Humidity", "Sensor 2"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_HUMIDITY_OFFSET_IN_0_1_HUMIDITY_SENSOR_2 (userEeprom[0x01be])

/**
		@brief Address: 01bf
		@li "Temperature factor in 0.1K", "Sensor 3"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_TEMPERATURE_OFFSET_IN_0_1K_SENSOR_3 (userEeprom[0x01bf])

/**
		@brief Address: 01c0
		@li "Humidity factor in 0.1%", "Humidity", "Sensor 3"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_HUMIDITY_OFFSET_IN_0_1_HUMIDITY_SENSOR_3 (userEeprom[0x01c0])

/**
		@brief Address: 01c1
		@li "Temperature factor in 0.1K", "Sensor 4"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_TEMPERATURE_OFFSET_IN_0_1K_SENSOR_4 (userEeprom[0x01c1])

/**
		@brief Address: 01c2
		@li "Humidity factor in 0.1%", "Humidity", "Sensor 4"
		@b Default: 0
			@brief factor Bits: 8 Type: signedInt from -100 to 100
*/
#define EE_HUMIDITY_OFFSET_IN_0_1_HUMIDITY_SENSOR_4 (userEeprom[0x01c2])

/**
		@brief Address: 01c3
		@li "Send if signal changes", "Temperature", "Sensor 1"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_TEMPERATURE_SENSOR_1 ((unsigned)userEeprom[0x01c3] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c3 BitOffset:1
		@li "Send if signal changes by [0.1K]", "Temperature", "Sensor 1"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1K_TEMPERATURE_SENSOR_1 (userEeprom[0x01c3] &~ (-1u << 7u))

/**
		@brief Address: 01c4
		@li "Send if signal changes", "Humidity", "Sensor 1"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_HUMIDITY_SENSOR_1 ((unsigned)userEeprom[0x01c4] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c4 BitOffset:1
		@li "Send if signal changes by [0.1% rH]", "Humidity", "Sensor 1"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1_RH_HUMIDITY_SENSOR_1 (userEeprom[0x01c4] &~ (-1u << 7u))

/**
		@brief Address: 01c5
		@li "Send if signal changes", "Temperature", "Sensor 2"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_TEMPERATURE_SENSOR_2 ((unsigned)userEeprom[0x01c5] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c5 BitOffset:1
		@li "Send if signal changes by [0.1K]", "Temperature", "Sensor 2"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1K_TEMPERATURE_SENSOR_2 (userEeprom[0x01c5] &~ (-1u << 7u))

/**
		@brief Address: 01c6
		@li "Send if signal changes", "Humidity", "Sensor 2"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_HUMIDITY_SENSOR_2 ((unsigned)userEeprom[0x01c6] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c6 BitOffset:1
		@li "Send if signal changes by [0.1% rH]", "Humidity", "Sensor 2"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1_RH_HUMIDITY_SENSOR_2 (userEeprom[0x01c6] &~ (-1u << 7u))

/**
		@brief Address: 01c7
		@li "Send if signal changes", "Temperature", "Sensor 3"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_TEMPERATURE_SENSOR_3 ((unsigned)userEeprom[0x01c7] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c7 BitOffset:1
		@li "Send if signal changes by [0.1K]", "Temperature", "Sensor 3"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1K_TEMPERATURE_SENSOR_3 (userEeprom[0x01c7] &~ (-1u << 7u))

/**
		@brief Address: 01c8
		@li "Send if signal changes", "Humidity", "Sensor 3"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_HUMIDITY_SENSOR_3 ((unsigned)userEeprom[0x01c8] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c8 BitOffset:1
		@li "Send if signal changes by [0.1% rH]", "Humidity", "Sensor 3"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1_RH_HUMIDITY_SENSOR_3 (userEeprom[0x01c8] &~ (-1u << 7u))

/**
		@brief Address: 01c9
		@li "Send if signal changes", "Temperature", "Sensor 4"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_TEMPERATURE_SENSOR_4 ((unsigned)userEeprom[0x01c9] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01c9 BitOffset:1
		@li "Send if signal changes by [0.1K]", "Temperature", "Sensor 4"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1K_TEMPERATURE_SENSOR_4 (userEeprom[0x01c9] &~ (-1u << 7u))

/**
		@brief Address: 01ca
		@li "Send if signal changes", "Humidity", "Sensor 4"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_IF_SIGNAL_CHANGES_HUMIDITY_SENSOR_4 ((unsigned)userEeprom[0x01ca] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01ca BitOffset:1
		@li "Send if signal changes by [0.1% rH]", "Humidity", "Sensor 4"
		@b Default: 10
			@brief messwert_diff Bits: 7 Type: unsignedInt from 1 to 125
*/
#define EE_SEND_IF_SIGNAL_CHANGES_BY_0_1_RH_HUMIDITY_SENSOR_4 (userEeprom[0x01ca] &~ (-1u << 7u))

/**
		@brief Address: 01cb
		@li "send periodically", "Temperature", "Sensor 1"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_TEMPERATURE_SENSOR_1 ((unsigned)userEeprom[0x01cb] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01cb BitOffset:1
		@li "Factor", "send periodically", "Temperature", "Sensor 1"
		@b Default: 50
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_TEMPERATURE_SENSOR_1 (userEeprom[0x01cb] &~ (-1u << 7u))

/**
		@brief Address: 01cc
		@li "send periodically", "Humidity", "Sensor 1"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_HUMIDITY_SENSOR_1 ((unsigned)userEeprom[0x01cc] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01cc BitOffset:1
		@li "Factor", "send periodically", "Humidity", "Sensor 1"
		@b Default: 52
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_HUMIDITY_SENSOR_1 (userEeprom[0x01cc] &~ (-1u << 7u))

/**
		@brief Address: 01cd
		@li "send periodically", "Temperature", "Sensor 2"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_TEMPERATURE_SENSOR_2 ((unsigned)userEeprom[0x01cd] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01cd BitOffset:1
		@li "Factor", "send periodically", "Temperature", "Sensor 2"
		@b Default: 50
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_TEMPERATURE_SENSOR_2 (userEeprom[0x01cd] &~ (-1u << 7u))

/**
		@brief Address: 01ce
		@li "send periodically", "Humidity", "Sensor 2"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_HUMIDITY_SENSOR_2 ((unsigned)userEeprom[0x01ce] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01ce BitOffset:1
		@li "Factor", "send periodically", "Humidity", "Sensor 2"
		@b Default: 52
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_HUMIDITY_SENSOR_2 (userEeprom[0x01ce] &~ (-1u << 7u))

/**
		@brief Address: 01cf
		@li "send periodically", "Temperature", "Sensor 3"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_TEMPERATURE_SENSOR_3 ((unsigned)userEeprom[0x01cf] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01cf BitOffset:1
		@li "Factor", "send periodically", "Temperature", "Sensor 3"
		@b Default: 50
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_TEMPERATURE_SENSOR_3 (userEeprom[0x01cf] &~ (-1u << 7u))

/**
		@brief Address: 01d0
		@li "send periodically", "Humidity", "Sensor 3"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_HUMIDITY_SENSOR_3 ((unsigned)userEeprom[0x01d0] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01d0 BitOffset:1
		@li "Factor", "send periodically", "Humidity", "Sensor 3"
		@b Default: 52
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_HUMIDITY_SENSOR_3 (userEeprom[0x01d0] &~ (-1u << 7u))

/**
		@brief Address: 01d1
		@li "send periodically", "Temperature", "Sensor 4"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_TEMPERATURE_SENSOR_4 ((unsigned)userEeprom[0x01d1] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01d1 BitOffset:1
		@li "Factor", "send periodically", "Temperature", "Sensor 4"
		@b Default: 50
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_TEMPERATURE_SENSOR_4 (userEeprom[0x01d1] &~ (-1u << 7u))

/**
		@brief Address: 01d2
		@li "send periodically", "Humidity", "Sensor 4"
		@b Default: 1
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_HUMIDITY_SENSOR_4 ((unsigned)userEeprom[0x01d2] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01d2 BitOffset:1
		@li "Factor", "send periodically", "Humidity", "Sensor 4"
		@b Default: 52
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_FACTOR_SEND_PERIODICALLY_HUMIDITY_SENSOR_4 (userEeprom[0x01d2] &~ (-1u << 7u))

/**
		@brief Address: 01d3
		@li "Timebase", "Humidity", "Sensor 1"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_HUMIDITY_SENSOR_1 ((unsigned)userEeprom[0x01d3] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01d3 BitOffset:4
		@li "Timebase", "Temperature", "Sensor 1"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_TEMPERATURE_SENSOR_1 (userEeprom[0x01d3] &~ (-1u << 4u))

/**
		@brief Address: 01d4
		@li "Timebase", "Humidity", "Sensor 2"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_HUMIDITY_SENSOR_2 ((unsigned)userEeprom[0x01d4] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01d4 BitOffset:4
		@li "Timebase", "Temperature", "Sensor 2"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_TEMPERATURE_SENSOR_2 (userEeprom[0x01d4] &~ (-1u << 4u))

/**
		@brief Address: 01d5
		@li "Timebase", "Humidity", "Sensor 3"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_HUMIDITY_SENSOR_3 ((unsigned)userEeprom[0x01d5] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01d5 BitOffset:4
		@li "Timebase", "Temperature", "Sensor 3"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_TEMPERATURE_SENSOR_3 (userEeprom[0x01d5] &~ (-1u << 4u))

/**
		@brief Address: 01d6
		@li "Timebase", "Humidity", "Sensor 4"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_HUMIDITY_SENSOR_4 ((unsigned)userEeprom[0x01d6] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01d6 BitOffset:4
		@li "Timebase", "Temperature", "Sensor 4"
		@b Default: 1
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_TIMEBASE_TEMPERATURE_SENSOR_4 (userEeprom[0x01d6] &~ (-1u << 4u))

/**
		@brief Address: 01d7 BitOffset:2
		@li "Association", "Threshold 3", "Sensor 1"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_3_SENSOR_1 ((unsigned)userEeprom[0x01d7] >> 4u &~ (-1u << 2u))

/**
		@brief Address: 01d7 BitOffset:4
		@li "Association", "Threshold 2", "Sensor 1"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_2_SENSOR_1 ((unsigned)userEeprom[0x01d7] >> 2u &~ (-1u << 2u))

/**
		@brief Address: 01d7 BitOffset:6
		@li "Association", "Threshold 1", "Sensor 1"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_1_SENSOR_1 (userEeprom[0x01d7] &~ (-1u << 2u))

/**
		@brief Address: 01d8 BitOffset:2
		@li "Association", "Threshold 3", "Sensor 2"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_3_SENSOR_2 ((unsigned)userEeprom[0x01d8] >> 4u &~ (-1u << 2u))

/**
		@brief Address: 01d8 BitOffset:4
		@li "Association", "Threshold 2", "Sensor 2"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_2_SENSOR_2 ((unsigned)userEeprom[0x01d8] >> 2u &~ (-1u << 2u))

/**
		@brief Address: 01d8 BitOffset:6
		@li "Association", "Threshold 1", "Sensor 2"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_1_SENSOR_2 (userEeprom[0x01d8] &~ (-1u << 2u))

/**
		@brief Address: 01d9 BitOffset:2
		@li "Association", "Threshold 3", "Sensor 3"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_3_SENSOR_3 ((unsigned)userEeprom[0x01d9] >> 4u &~ (-1u << 2u))

/**
		@brief Address: 01d9 BitOffset:4
		@li "Association", "Threshold 2", "Sensor 3"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_2_SENSOR_3 ((unsigned)userEeprom[0x01d9] >> 2u &~ (-1u << 2u))

/**
		@brief Address: 01d9 BitOffset:6
		@li "Association", "Threshold 1", "Sensor 3"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_1_SENSOR_3 (userEeprom[0x01d9] &~ (-1u << 2u))

/**
		@brief Address: 01da BitOffset:2
		@li "Association", "Threshold 3", "Sensor 4"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_3_SENSOR_4 ((unsigned)userEeprom[0x01da] >> 4u &~ (-1u << 2u))

/**
		@brief Address: 01da BitOffset:4
		@li "Association", "Threshold 2", "Sensor 4"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_2_SENSOR_4 ((unsigned)userEeprom[0x01da] >> 2u &~ (-1u << 2u))

/**
		@brief Address: 01da BitOffset:6
		@li "Association", "Threshold 1", "Sensor 4"
		@b Default: 1
			@brief grenzwert_zuordnung Bits: 2
				@ref GRENZWERT_ZUORDNUNG_TEMPERATURE (1): lux
				@ref GRENZWERT_ZUORDNUNG_HUMIDITY (2): humidity
*/
#define EE_ASSOCIATION_THRESHOLD_1_SENSOR_4 (userEeprom[0x01da] &~ (-1u << 2u))

/**
		@brief Address: 01db
		@li "Send if", "Threshold 2", "Sensor 1"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_2_SENSOR_1 ((unsigned)userEeprom[0x01db] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01db BitOffset:4
		@li "Send if", "Threshold 1", "Sensor 1"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_1_SENSOR_1 (userEeprom[0x01db] &~ (-1u << 4u))

/**
		@brief Address: 01dc
		@li "Send periodically, timebase", "Threshold 1", "Sensor 1"
		@b Default: 0
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_SEND_PERIODICALLY_TIMEBASE_THRESHOLD_1_SENSOR_1 ((unsigned)userEeprom[0x01dc] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01dc BitOffset:4
		@li "Send if", "Threshold 3", "Sensor 1"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_3_SENSOR_1 (userEeprom[0x01dc] &~ (-1u << 4u))

/**
		@brief Address: 01dd
		@li "Send if", "Threshold 2", "Sensor 2"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_2_SENSOR_2 ((unsigned)userEeprom[0x01dd] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01dd BitOffset:4
		@li "Send if", "Threshold 1", "Sensor 2"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_1_SENSOR_2 (userEeprom[0x01dd] &~ (-1u << 4u))

/**
		@brief Address: 01de
		@li "Send periodically, timebase", "Threshold 1", "Sensor 2"
		@b Default: 0
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_SEND_PERIODICALLY_TIMEBASE_THRESHOLD_1_SENSOR_2 ((unsigned)userEeprom[0x01de] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01de BitOffset:4
		@li "Send if", "Threshold 3", "Sensor 2"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_3_SENSOR_2 (userEeprom[0x01de] &~ (-1u << 4u))

/**
		@brief Address: 01df
		@li "Send if", "Threshold 2", "Sensor 3"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_2_SENSOR_3 ((unsigned)userEeprom[0x01df] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01df BitOffset:4
		@li "Send if", "Threshold 1", "Sensor 3"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_1_SENSOR_3 (userEeprom[0x01df] &~ (-1u << 4u))

/**
		@brief Address: 01e0
		@li "Send periodically, timebase", "Threshold 1", "Sensor 3"
		@b Default: 0
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_SEND_PERIODICALLY_TIMEBASE_THRESHOLD_1_SENSOR_3 ((unsigned)userEeprom[0x01e0] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01e0 BitOffset:4
		@li "Send if", "Threshold 3", "Sensor 3"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_3_SENSOR_3 (userEeprom[0x01e0] &~ (-1u << 4u))

/**
		@brief Address: 01e1
		@li "Send if", "Threshold 2", "Sensor 4"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_2_SENSOR_4 ((unsigned)userEeprom[0x01e1] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01e1 BitOffset:4
		@li "Send if", "Threshold 1", "Sensor 4"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_1_SENSOR_4 (userEeprom[0x01e1] &~ (-1u << 4u))

/**
		@brief Address: 01e2
		@li "Send periodically, timebase", "Threshold 1", "Sensor 4"
		@b Default: 0
			@brief timer_basis Bits: 4
				@ref TIMER_BASIS_130_MS (0): 130 ms
				@ref TIMER_BASIS_260_MS (1): 260 ms
				@ref TIMER_BASIS_520_MS (2): 520 ms
				@ref TIMER_BASIS_1_0_S (3): 1.0 s
				@ref TIMER_BASIS_2_1_S (4): 2.1 s
				@ref TIMER_BASIS_4_2_S (5): 4.2 s
				@ref TIMER_BASIS_8_4_S (6): 8.4 s
				@ref TIMER_BASIS_17_S (7): 17 s
				@ref TIMER_BASIS_34_S (8): 34 s
				@ref TIMER_BASIS_1_1_MIN (9): 1.1 min
				@ref TIMER_BASIS_2_2_MIN (10): 2.2 min
				@ref TIMER_BASIS_4_5_MIN (11): 4.5 min
				@ref TIMER_BASIS_9_MIN (12): 9 min
				@ref TIMER_BASIS_18_MIN (13): 18 min
				@ref TIMER_BASIS_35_MIN (14): 35 min
				@ref TIMER_BASIS_1_2_H (15): 1.2 h
*/
#define EE_SEND_PERIODICALLY_TIMEBASE_THRESHOLD_1_SENSOR_4 ((unsigned)userEeprom[0x01e2] >> 4u &~ (-1u << 4u))

/**
		@brief Address: 01e2 BitOffset:4
		@li "Send if", "Threshold 3", "Sensor 4"
		@b Default: 14
			@brief grenzwert_reaktion Bits: 4
				@ref GRENZWERT_REAKTION_DEACTIVATED (0): deactivated
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0 (2): falls below --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1 (3): falls below --> 1
				@ref GRENZWERT_REAKTION_EXCEED_0 (8): exceed --> 0
				@ref GRENZWERT_REAKTION_EXCEED_1 (12): exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_1 (14): falls below --> 0 / exceed --> 1
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_0 (11): falls below --> 1 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_0_EXCEED_0 (10): falls below --> 0 / exceed --> 0
				@ref GRENZWERT_REAKTION_FALLS_BELOW_1_EXCEED_1 (15): falls below --> 1 / exceed --> 1
*/
#define EE_SEND_IF_THRESHOLD_3_SENSOR_4 (userEeprom[0x01e2] &~ (-1u << 4u))

/**
		@brief Address: 01e3
		@li "send periodically", "Threshold 1", "Sensor 1"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_THRESHOLD_1_SENSOR_1 ((unsigned)userEeprom[0x01e3] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01e3 BitOffset:1
		@li "Send periodically, factor", "Threshold 1", "Sensor 1"
		@b Default: 3
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_SEND_PERIODICALLY_FACTOR_THRESHOLD_1_SENSOR_1 (userEeprom[0x01e3] &~ (-1u << 7u))

/**
		@brief Address: 01e4
		@li "send periodically", "Threshold 1", "Sensor 2"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_THRESHOLD_1_SENSOR_2 ((unsigned)userEeprom[0x01e4] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01e4 BitOffset:1
		@li "Send periodically, factor", "Threshold 1", "Sensor 2"
		@b Default: 3
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_SEND_PERIODICALLY_FACTOR_THRESHOLD_1_SENSOR_2 (userEeprom[0x01e4] &~ (-1u << 7u))

/**
		@brief Address: 01e5
		@li "send periodically", "Threshold 1", "Sensor 3"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_THRESHOLD_1_SENSOR_3 ((unsigned)userEeprom[0x01e5] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01e5 BitOffset:1
		@li "Send periodically, factor", "Threshold 1", "Sensor 3"
		@b Default: 3
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_SEND_PERIODICALLY_FACTOR_THRESHOLD_1_SENSOR_3 (userEeprom[0x01e5] &~ (-1u << 7u))

/**
		@brief Address: 01e6
		@li "send periodically", "Threshold 1", "Sensor 4"
		@b Default: 0
			@brief ja_nein Bits: 1
				@ref JA_NEIN_NO (0): no
				@ref JA_NEIN_YES (1): yes
*/
#define EE_SEND_PERIODICALLY_THRESHOLD_1_SENSOR_4 ((unsigned)userEeprom[0x01e6] >> 7u &~ (-1u << 1u))

/**
		@brief Address: 01e6 BitOffset:1
		@li "Send periodically, factor", "Threshold 1", "Sensor 4"
		@b Default: 3
			@brief timer_faktor Bits: 7 Type: unsignedInt from 3 to 127
*/
#define EE_SEND_PERIODICALLY_FACTOR_THRESHOLD_1_SENSOR_4 (userEeprom[0x01e6] &~ (-1u << 7u))

/**
		@brief Address: 01e7
		@li "Value in 0.1K", "Threshold 1", "Sensor 1"
		@b Default: 200 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 1", "Sensor 1"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_1_SENSOR_1 (((unsigned)userEeprom[0x01e7] << 8u) \
		|  userEeprom[0x01e8])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_1_SENSOR_1 (((unsigned)userEeprom[0x01e7] << 8u) \
		|  userEeprom[0x01e8])

/**
		@brief Address: 01e9
		@li "Value in 0.1K", "Threshold 2", "Sensor 1"
		@b Default: 230 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 2", "Sensor 1"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_2_SENSOR_1 (((unsigned)userEeprom[0x01e9] << 8u) \
		|  userEeprom[0x01ea])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_2_SENSOR_1 (((unsigned)userEeprom[0x01e9] << 8u) \
		|  userEeprom[0x01ea])

/**
		@brief Address: 01eb
		@li "Value in 0.1K", "Threshold 3", "Sensor 1"
		@b Default: 250 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 3", "Sensor 1"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_3_SENSOR_1 (((unsigned)userEeprom[0x01eb] << 8u) \
		|  userEeprom[0x01ec])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_3_SENSOR_1 (((unsigned)userEeprom[0x01eb] << 8u) \
		|  userEeprom[0x01ec])

/**
		@brief Address: 01ed
		@li "Value in 0.1K", "Threshold 1", "Sensor 2"
		@b Default: 200 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 1", "Sensor 2"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_1_SENSOR_2 (((unsigned)userEeprom[0x01ed] << 8u) \
		|  userEeprom[0x01ee])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_1_SENSOR_2 (((unsigned)userEeprom[0x01ed] << 8u) \
		|  userEeprom[0x01ee])

/**
		@brief Address: 01ef
		@li "Value in 0.1K", "Threshold 2", "Sensor 2"
		@b Default: 230 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 2", "Sensor 2"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_2_SENSOR_2 (((unsigned)userEeprom[0x01ef] << 8u) \
		|  userEeprom[0x01f0])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_2_SENSOR_2 (((unsigned)userEeprom[0x01ef] << 8u) \
		|  userEeprom[0x01f0])

/**
		@brief Address: 01f1
		@li "Value in 0.1K", "Threshold 3", "Sensor 2"
		@b Default: 250 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 3", "Sensor 2"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_3_SENSOR_2 (((unsigned)userEeprom[0x01f1] << 8u) \
		|  userEeprom[0x01f2])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_3_SENSOR_2 (((unsigned)userEeprom[0x01f1] << 8u) \
		|  userEeprom[0x01f2])

/**
		@brief Address: 01f3
		@li "Value in 0.1K", "Threshold 1", "Sensor 3"
		@b Default: 200 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 1", "Sensor 3"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_1_SENSOR_3 (((unsigned)userEeprom[0x01f3] << 8u) \
		|  userEeprom[0x01f4])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_1_SENSOR_3 (((unsigned)userEeprom[0x01f3] << 8u) \
		|  userEeprom[0x01f4])

/**
		@brief Address: 01f5
		@li "Value in 0,1% rH", "Threshold 2", "Sensor 3"
		@b Default: 0 DEFAULT
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
		@li "Value in 0.1K", "Threshold 2", "Sensor 3"
		@b Default: 230
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
*/
#define EE_VALUE_IN_0_1_RH_THRESHOLD_2_SENSOR_3 (((unsigned)userEeprom[0x01f5] << 8u) \
		|  userEeprom[0x01f6])
#define EE_VALUE_IN_0_1K_THRESHOLD_2_SENSOR_3 (((unsigned)userEeprom[0x01f5] << 8u) \
		|  userEeprom[0x01f6])

/**
		@brief Address: 01f7
		@li "Value in 0.1K", "Threshold 3", "Sensor 3"
		@b Default: 250 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 3", "Sensor 3"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
		@li "Value in 0.1K", "Threshold 1", "Sensor 4"
		@b Default: 200 Offset: 2
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 1", "Sensor 4"
		@b Default: 0 Offset: 2
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_3_SENSOR_3 (((unsigned)userEeprom[0x01f7] << 8u) \
		|  userEeprom[0x01f8])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_3_SENSOR_3 (((unsigned)userEeprom[0x01f7] << 8u) \
		|  userEeprom[0x01f8])
#define EE_VALUE_IN_0_1K_THRESHOLD_1_SENSOR_4 (((unsigned)userEeprom[0x01f9] << 8u) \
		|  userEeprom[0x01fa])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_1_SENSOR_4 (((unsigned)userEeprom[0x01f9] << 8u) \
		|  userEeprom[0x01fa])

/**
		@brief Address: 01fb
		@li "Value in 0.1K", "Threshold 2", "Sensor 4"
		@b Default: 230 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 2", "Sensor 4"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_2_SENSOR_4 (((unsigned)userEeprom[0x01fb] << 8u) \
		|  userEeprom[0x01fc])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_2_SENSOR_4 (((unsigned)userEeprom[0x01fb] << 8u) \
		|  userEeprom[0x01fc])

/**
		@brief Address: 01fd
		@li "Value in 0.1K", "Threshold 3", "Sensor 4"
		@b Default: 250 DEFAULT
			@brief grenzwert Bits: 16 Type: signedInt from -500 to 1200
		@li "Value in 0,1% rH", "Threshold 3", "Sensor 4"
		@b Default: 0
			@brief grenzwert_feuchtigkeit Bits: 16 Type: unsignedInt from 0 to 1000
*/
#define EE_VALUE_IN_0_1K_THRESHOLD_3_SENSOR_4 (((unsigned)userEeprom[0x01fd] << 8u) \
		|  userEeprom[0x01fe])
#define EE_VALUE_IN_0_1_RH_THRESHOLD_3_SENSOR_4 (((unsigned)userEeprom[0x01fd] << 8u) \
		|  userEeprom[0x01fe])

#endif /* INC_LIGHTSENSOR_PARAMS_H */
