/*
 * crc.h
 *
 * Code generated by universal_crc by Danjel McGougan
 *
 * CRC parameters used:
 *   bits:       8
 *   poly:       0x07
 *   init:       0xff
 *   xor:        0x00
 *   reverse:    false
 *   non-direct: false
 *
 * CRC of the string "123456789" is 0xfb
 */

#ifndef CRC_H_
#define CRC_H_

#include <stddef.h>
#include <stdint.h>

uint8_t crc_calc(const uint8_t *data, size_t len);

#endif
